name: CI - Terraform checks

on:
  pull_request:
  push:
    branches: [ master ]

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init (no-backend)
        run: terraform init -backend=false
        working-directory: ./terraform

      - name: Terraform Fmt check
        run: terraform fmt -check
        working-directory: ./terraform

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./terraform
