name: Terraform Plan (PR) / Apply (merge)

on:
  pull_request:
    paths:
      - 'terraform/**'
  push:
    branches: [ master ]

jobs:
  plan:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Terraform Init
        run: terraform init -backend=false
        working-directory: .
      - name: Terraform Plan
        run: terraform plan -no-color
        working-directory: .

  apply:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: [plan]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Terraform Init
        run: terraform init
        working-directory: .
      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: .
